### PR TITLE
Update dateFormat

### PR DESCRIPTION
**Pull request by scottleibrand**
Use international standard date notation (YYYY-MM-DD), and include timezone.

### CODE REVIEW

**Comment by i-schuetz** [comment]
Just curious, why do we show the users their timezone?

**Comment by scottleibrand** [comment]
Because if you don't, I wonder if it's displaying in local time or UTC.

**Comment by i-schuetz** [comment]
It's local time. I tested it when uploading the format.

**Comment by scottleibrand** [comment]
Yeah, but it used to be UTC, so best to just show people it's PDT or CET so it's unambiguous.

**Comment by scottleibrand** [comment]
image

**Comment by scottleibrand** [comment]
Built locally and ran it on my phone, and it looks good to me.

**Pull request merged**
