### PR TITLE
#281 Remove superfluous symptom report screen

### LINKED ISSUE #281: Remove symptom specific duration screens.
As identified in https://github.com/Co-Epi/app-android/issues/244, remove the symptom specific duration screens since we anchor on the earliest symptom date.

### PR DESCRIPTION
**Pull request by Sam-gtri**
Details from issue 281

https://github.com/Co-Epi/app-ios/issues/281

### CODE REVIEW

**Comment by astewart43-gtri** [comment]
@Sam-gtri I think this may be backwards. 
My understanding was that the cough and fever days should be removed, and only include the general one. 
It looks like this branch has left the cough and fever and removed the general one.

@i-schuetz, @danamlewis, or @mellowgeek  please correct me if I am wrong.

**Comment by danamlewis** [comment]
Correct, general symptom date (for all symptoms) should be kept; remove the symptom-specific date query.

**Comment by Sam-gtri** [comment]
@astewart43-gtri Ill work on that!

**Review by ivnsch — CHANGES_REQUESTED** [review]
See comments

**Comment by Sam-gtri** [comment]
I just made the changes so that only fever and cough reports were affected. 

Let me know if you want me to make any additional changes for this PR

@i-schuetz @astewart43-gtri

**Comment by Sam-gtri** [comment]
@astewart43-gtri @i-schuetz

**Review by ivnsch — APPROVED** [review]

**Pull request merged**
