### PR TITLE
added What are exposure  alerts

### LINKED ISSUE #221: Implement "What are exposure  alerts?" screen
The modal is already wired. Add contents from Figma.

### PR DESCRIPTION
**Pull request by astewart43-gtri**
closes #221

### CODE REVIEW

**Comment by ivnsch** [comment]
Can't this be rendered as HTML? E.g. using attributed string https://developer.apple.com/documentation/uikit/nshtmltextdocumenttype

**Comment by astewart43-gtri** [comment]
perhaps? I am using attributed strings.

**Comment by ivnsch** [comment]
Yeah, I mean as a single attributed string, this is very tedious to maintain and not localization friendly. https://stackoverflow.com/questions/37048759/swift-display-html-data-in-a-label-or-textview

**Comment by astewart43-gtri** [comment]
gotcha. so are you saying you would prefer one label for the entire text body?

**Comment by ivnsch** [comment]
yes

**Review by ivnsch — CHANGES_REQUESTED** [review]
Updating PR status (requires comment)

**Review by ivnsch — APPROVED** [review]

**Pull request merged**
